require('nomiclabs/hardhat-waffle');
module.exports={
  solidity:'0.8.0',
  networks:{
    goerli:{
      url:'https://eth-goerli.g.alchemy.com/v2/6b9uaEPAqUpQnDg3gLmNZAI3cBG-KdBc',
      accounts:[]
    }
  }
}